#!/bin/bash
BUCKET=s3://ly-do.com
DISTRIBUTION_ID=E27KQGU3JT3EX2

# Remove all existing files in the bucket
echo "Deleting all existing files in the bucket"
aws s3 --profile lydo rm "$BUCKET" --recursive

# Upload from dist folder
echo "Uploading files in the dist folder"
aws s3 --profile lydo cp dist/personal-website "$BUCKET" --recursive

# Invalidate cache from CloudFront

aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"